### ISSUE TITLE
adding new dup and swap things

### ISSUE THREAD

**Issue by realfinder** [pinterf/masktools#13]
Hi
1st is in infix/polish https://forum.doom9.org/showpost.php?p=1879768&postcount=328

2nd is new dupN and swapN as in avs+ expr() in both mt_lut* and infix/polish

thanks

**Comment by pinterf** [comment]
Not tested, please have a look at it:
https://drive.google.com/file/d/1WGU7NH9KP6FzCN-jLIYhU_ZuRLZdEZ1O/view?usp=sharing

**Comment by realfinder** [comment]
I tried this Mt_lutxy(last, blur(1), "x y - abs dup dup 111 < swap2 2 * ?") base on some VS code and it give same output as expr(last, blur(1), "x y - abs dup dup 111 < swap2 2 * ?") so I think it work, didn't find code with dupN now (since vs guys post code in discord so its not something organized)

anyway, with MessageClip(mt_infix(" x range_half - dup * dup y range_half - dup * + / range_max *"))
will be
![image](https://user-images.githubusercontent.com/2512153/89492917-74ffd180-d7bb-11ea-919b-e0f945c3a60d.png)
and MessageClip(mt_infix("x y - dup * 3 * x y + range_size - 2 ^ - range_half +"))
will be
![image](https://user-images.githubusercontent.com/2512153/89493018-b7c1a980-d7bb-11ea-89f6-bb55b0ff64ed.png)
both from [srestore](https://raw.githubusercontent.com/realfinder/AVS-Stuff/master/avs%202.5%20and%20up/Srestore.avsi) I think it's not look good but better than nothing

**Comment by pinterf** [comment]
I am not able to implement infix (even a simple dup) without deeper modification, stack operations are not too friendly in this aspect.

**Comment by pinterf** [comment]
Did any further tests happen on dupN swapN?

**Comment by realfinder** [comment]
I did another simple test

Mt_lut("range_max range_half + range_min dup1 - -")
expr("range_max range_half + range_min dup1 - -")

the output of Mt_lut not same as expr here, I think dupN not work or something

but this work

Mt_lut("range_min range_half + range_min dup1 + +")
expr("range_min range_half + range_min dup1 + +")

edit: also this work 
Mt_lut("range_min range_half + range_half dup1 - +")
expr("range_min range_half + range_half dup1 - +")

**Comment by pinterf** [comment]
Thanks, try this build
https://drive.google.com/file/d/1cmlSOFCPRy5uCAXQCSjy6sIQn7v_i8QB/view?usp=sharing

**Comment by realfinder** [comment]
yes, that work for the first one, thanks
