### ISSUE TITLE
use_expr=3 and classic avs 2.6

### ISSUE THREAD

**Issue by realfinder** [pinterf/masktools#14]
Hi
seems there are problem with avs 2.6 and maybe older avs+ that don't has expr() with use_expr=3
```
ColorBars(width=640, height=480, pixel_type="yv12")
mt_lutxy( Blur(1), "x range_half - y * range_size / range_half +", scale_inputs="floatf", use_expr=3)
```
using avs 2.6 mt by SEt it give some error in avspmod "WindowsError: [Error -529697949] Windows Error 0xE06D7363"
in other programs it crash

**Comment by pinterf** [comment]
No wonder. Don't set use_expr for avisynth versions which do not support it.
Anyway, I'm preparing a version which is giving proper message, like this:
"Error on invoking "Expr" call with use_expr: not found!"

**Comment by realfinder** [comment]
the problem is I use it in QTGMC and another scripts, so maybe it's better to make it silently force use_expr=0 instead of Error message

**Comment by pinterf** [comment]
Let it be, stay tuned.

**Comment by pinterf** [comment]
Try this build:
https://drive.google.com/file/d/1S5_W5aBpMu-EYO4B4nWtfkE-FOS1LZId/view?usp=sharing

**Comment by realfinder** [comment]
that work, thanks

**Comment by pinterf** [comment]
released
