### ISSUE TITLE
TAB, CR and LF characters in mt_lut*

### ISSUE THREAD

**Issue by realfinder** [pinterf/masktools#21]
same as https://github.com/AviSynth/AviSynthPlus/commit/a11711d43b1420fbf9b432dfcd44d95b4ebc68dd

**Comment by pinterf** [comment]
Good idea.

**Comment by pinterf** [comment]
Test build, could you please test it? If works, goes to release.
https://drive.google.com/uc?export=download&id=14Q8lqNMDGrtZKnlh1xhJUs4gjARqmkQw
Thank you

**Comment by realfinder** [comment]
seems work, thanks

**Comment by pinterf** [comment]
Released 2.2.28
