### ISSUE TITLE
Boost libary should update to V142 too.

### ISSUE THREAD

**Issue by fuchanghao** [pinterf/masktools#5]
From Boost 1.70.0 it already has lib64-msvc-14.2 and lib32-msvc-14.2.

now common use msvc-14.0 and masktools use msvc-14.1.

see boost_1_70_0-unsupported-bin-msvc-all-32-64.7z

https://sourceforge.net/projects/boost/files/boost-binaries/1.70.0/

Other small issues should fix.

1. c:\Github\masktools\masktools\avsheaders\ should change to ..\avsheaders\
2. some $(WindowsSdk_71A_LibraryPath_x64) should $(WindowsSdk_LibraryPath_x64)
3. missing " in \common\parser\symbol.cpp and ' & masktools\helpers\parser\spirit.cpp line 163 should be 

> ('?' >> term5)[AddNamedSymbol("?", self.rpn)] |

**Comment by pinterf** [comment]
This latter error (missing...) is coming after 1.70 boost update?
(Plus there is a helper comment onhow to include boost libs into the project, it should be updated as well)

**Comment by fuchanghao** [comment]
> 
> 
> This latter error (missing...) is coming after 1.70 boost update?
> (Plus there is a helper comment onhow to include boost libs into the project, it should be updated as well)

\common\parser\symbol.cpp line 169 changed to

> Symbol Symbol::Xor            ("?" , "@", OPERATOR, xor);

and masktools\helpers\parser\spirit.cpp line 163 changed to

> ('?' >> term5)[AddNamedSymbol("?", self.rpn)] |

I have to change like that for working fine on my platform:

Boost 1.70.0
Visual Studio 2019+MSVC 142
Windows 10.0.18362.0 (1903) SDK

**Comment by pinterf** [comment]
That '?' is '°' in real life, which seems somewhat problematic to display on your language settings. I think the the uglyness of the '°' (degree) symbol was the reason for introducing @ sign besides this character.

**Comment by fuchanghao** [comment]
> 
> 
> That '?' is '°' in real life, which seems somewhat problematic to display on your language settings. I think the the uglyness of the '°' (degree) symbol was the reason for introducing @ sign besides this character.

if that so it should write as "°" instead of '°'

**Comment by fuchanghao** [comment]
> 
> 
> That '?' is '°' in real life, which seems somewhat problematic to display on your language settings. I think the the uglyness of the '°' (degree) symbol was the reason for introducing @ sign besides this character.

Find what happened really.

The code of spirit.cpp and symbol.cpp is Western (Windows 1252), you'd better open it with VSCode and save it with UTF-8. Western (Windows 1252) in some non-english Windows System.

Files after edit. (r506)

https://mega.nz/#F!1NZy2KyA!lb_K6sjqFN2DH11hSr5Ssw

**Comment by pinterf** [comment]
Thanks, I rather replaced them with hex representation it should be represent as one single byte char

**Comment by fuchanghao** [comment]
> 
> 
> Thanks, I rather replaced them with hex representation it should be represent as one single byte char

Still, the problem not solved in this commit.

https://github.com/pinterf/masktools/commit/4a00141e3a45a6c71669b67ba8ad3c7f05be3712

In my computer it showed as:

> ("\xB0" >> term5)[AddNamedSymbol("?, self.rpn)] |

PS: common/build/common.vcxproj still use c:\Github\masktools\masktools\avsheaders\
