### ISSUE TITLE
Can't build with VS2019 build-in LLVM/clang-cl.

### ISSUE THREAD

**Issue by fuchanghao** [pinterf/masktools#8]
I switch the LLVM to Clang-cl because of LLVM Compiler Toolchain only support VS2017.

https://marketplace.visualstudio.com/items?itemName=LLVMExtensions.llvm-toolchain

But it got error when I change the LLVM to build-in LLVM/clang-cl in release-llvm-boost.

> 1>..\parser\symbol.cpp(797,15): warning : enumeration value 'VARIABLE_UNDEFINED' not handled in switch [-Wswitch]
> 1>/LTCG: no such file or directory
> 1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(1272,5): error MSB6006: “llvm-lib.exe”已退出，代码为 1。

PS: MSVC 142 release-boost build works fine.

**Comment by pinterf** [comment]
Updated project with actual SDK versions, modded LLVM, added LLVM-clangCL

**Comment by fuchanghao** [comment]
> 
> 
> Updated project with actual SDK versions, modded LLVM, added LLVM-clangCL

After this change, I can't build x64 build after I build win32 build.

which I think should be

https://github.com/pinterf/masktools/blob/16bit/masktools/build/masktools.sln#L45

> 		{DBFBE277-5B8D-4258-B522-13146FD1E722}.release-LLVM-boost|Win32.ActiveCfg = release-LLVM-boost|Win32
> 		{DBFBE277-5B8D-4258-B522-13146FD1E722}.release-LLVM-boost|Win32.Build.0 = release-LLVM-boost|Win32
> 		{DBFBE277-5B8D-4258-B522-13146FD1E722}.release-LLVM-boost|x64.ActiveCfg = release-LLVM-boost|x64
> 		{DBFBE277-5B8D-4258-B522-13146FD1E722}.release-LLVM-boost|x64.Build.0 = release-LLVM-boost|x64
> 		{DBFBE277-5B8D-4258-B522-13146FD1E722}.release-LLVM-clangCL|Win32.ActiveCfg = release-LLVM-clangCL|Win32
> 		{DBFBE277-5B8D-4258-B522-13146FD1E722}.release-LLVM-clangCL|Win32.Build.0 = release-LLVM-clangCL|Win32
> 		{DBFBE277-5B8D-4258-B522-13146FD1E722}.release-LLVM-clangCL|x64.ActiveCfg = release-LLVM-clangCL|x64
> 		{DBFBE277-5B8D-4258-B522-13146FD1E722}.release-LLVM-clangCL|x64.Build.0 = release-LLVM-clangCL|x64


https://github.com/pinterf/masktools/blob/16bit/masktools/build/masktools.sln#L77

> 		{185396D8-57BD-4DDF-8CD3-26035EA50DB9}.release-LLVM-boost|Win32.ActiveCfg = release-LLVM-boost|Win32
> 		{185396D8-57BD-4DDF-8CD3-26035EA50DB9}.release-LLVM-boost|Win32.Build.0 = release-LLVM-boost|Win32
> 		{185396D8-57BD-4DDF-8CD3-26035EA50DB9}.release-LLVM-boost|x64.ActiveCfg = release-LLVM-boost|x64
> 		{185396D8-57BD-4DDF-8CD3-26035EA50DB9}.release-LLVM-boost|x64.Build.0 = release-LLVM-boost|x64
> 		{185396D8-57BD-4DDF-8CD3-26035EA50DB9}.release-LLVM-clangCL|Win32.ActiveCfg = release-LLVM-clangCL|Win32
> 		{185396D8-57BD-4DDF-8CD3-26035EA50DB9}.release-LLVM-clangCL|Win32.Build.0 = release-LLVM-clangCL|Win32
> 		{185396D8-57BD-4DDF-8CD3-26035EA50DB9}.release-LLVM-clangCL|x64.ActiveCfg = release-LLVM-clangCL|x64
> 		{185396D8-57BD-4DDF-8CD3-26035EA50DB9}.release-LLVM-clangCL|x64.Build.0 = release-LLVM-clangCL|x64

**Comment by fuchanghao** [comment]
works fine now:https://github.com/pinterf/masktools/commit/64efe33d201adecf3fd31bb4ca691fd4b6642093
